global:
  scrape_interval: 5s
  external_labels:
    monitor: 'infra-monitor'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prom-server:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'host.docker.internal:9093'