apiVersion: v1
kind: Service
metadata:
  name: prom-webhook
  namespace: prometheus
spec:
  selector:
    app: prom-webhook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP