global:
receivers:
  - name: default-receiver
  - name: ycap-webhook
    webhook_configs:
      - url: "http://host.docker.internal:3000/sms"

route:
  group_wait: 5s
  group_interval: 5s
  receiver: ycap-webhook
  repeat_interval: 5s
  
  routes: 
    - receiver: ycap-webhook
      match_re:
        app: ycap