version: '3.7'
services:
  prom-server:
    image: prom/prometheus
    volumes:
      - $PWD/prometheus.yaml:/etc/prometheus/prometheus.yml
      - $PWD/rules.yaml:/etc/prometheus/alert.rules
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100

  alert-manager:
    image: prom/alertmanager
    volumes:
      - $PWD/alertmanager.yaml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093