groups:
  - name: infra_service
    rules:
      - alert: monitor_service_down
        expr: go_goroutines{instance="host.docker.internal:3000",job="application_collector"} > 1
        for: 5s
        labels:
          app: app_server
          severity: critical
        annotations:
          summary: "Monitor service non-operational"
          description: "Service {{ $labels.instance }} is down."
